### ISSUE TITLE
Loading surfaces from other sources than filepaths

### ISSUE THREAD

**Issue by LucvandenBrand** [jobtalle/myr.js#35]
- From File objects
- From Image objects
- From a byte array
- From a base64 string

**Comment by jobtalle** [comment]
Possibly redundant if base64 can be passed and if #16 is implemented

**Comment by jobtalle** [comment]
I think this one has been covered sufficiently by pull request #44. Shall we close this one?

**Comment by LucvandenBrand** [comment]
Yep.
